version: 2.1

defaults: &defaults
  docker:
    - image: circleci/android:api-28
  environment:
    JVM_OPTS: -Xmx3200m
orbs:
  slack: circleci/slack@3.2.0

jobs:
  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Run the unit tests
          command: bundle exec fastlane unit_tests
      - store_artifacts:
          path: app/build/reports
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

  instrumentation-tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Store service account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize to gcloud
          command: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json --project=${GOOGLE_PROJECT_ID}
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: Start container and verify it is working
          command: |
            set -x
            docker-compose up -d
            docker run --network container:contacts \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/contacts/test
      - run:
          name: Run the instrumentation tests docker container
          command: bundle exec fastlane espresso_tests
      - store_artifacts:
          path: app/build/reports
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

  deploy-internal:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Store the google play key
          command: echo $GOOGLE_PLAY_KEY > gplay_key.json
      - run:
          name: Init fastlane supply
          command: bundle exec fastlane supply init
      - run:
          name: Download ci's data
          command: ./ci/download_ci_data.sh
      - run:
          name: Deploy the app to the internal track
          command: bundle exec fastlane deploy_internal
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  deploy-crashlytics:
      <<: *defaults
      steps:
        - checkout
        - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
            name: Install fastlane
            command: bundle install
        - run:
            name: Deploy the app to crashlytics for internal testing
            command: bundle exec fastlane beta
        - save_cache:
            paths:
              - ~/.gradle
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}


workflows:
  version: 2
  nighly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - instrumentation-tests
  deploy-crashlytics:
    jobs:
      - unit-tests:
          filters:
            branches:
              only:
                - /internal.*/
      - deploy-crashlytics:
          requires:
            - unit-tests

  deploy-internal:
    jobs:
      - unit-tests:
          filters:
            branches:
              only:
                - /internal.*/
      - instrumentation-tests:
          filters:
            branches:
              only:
                - /internal.*/
      - hold:
          type: approval
          filters:
            branches:
              only:
                - /internal.*/
          requires:
            - unit-tests
            - instrumentation-tests
      - deploy-internal:
          filters:
            branches:
              only:
                - /internal.*/
          requires:
            - hold
