# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
opt_out_usage

default_platform(:android)
platform :android do
  before_all do
      ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
      increment_version_code
    end
  desc "Run the unit tests"
  lane :unit_tests do
    gradle(task: "test")
  end

  desc "Assemble a debug apk"
  lane :assemble_debug do
    gradle(task: "assembleDebug")
  end

  desc "Assemble an android test apk"
  lane :assemble_android_test do
    gradle(task: "assembleDebugAndroidTest")
  end

  desc "Run the instrumentation tests in the Firebase test lab"
  lane :instrumentation_tests do
    gradle(task: "assembleDebugAndroidTest")
    gradle(task: "assembleDebug")
    sh("../ci/run_firebase_tests.sh")
  end
  desc "Submit a new Beta Build to Crashlytics Beta"
    lane :beta do
      gradle(task: "clean assembleDebug")
      crashlytics
     end

  desc "Deploy the app to the internal track"
  lane :deploy_internal do
    gradle(task: "bundleRelease")
    supply(
      track: 'internal',
      aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH].to_s
    )
    end
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
  after_all do |beta|
   # This block is called, only if the executed lane was successful
       slack(
         message: "Successfully deployed new App to Crashlytics."
         fail_on_error : true
      )
    end
    after_all do |instrumentation_tests|
       # This block is called, only if the executed lane was successful
           slack(
             message: "App successfully released!",
             fail_on_error : true,
             payload: {
               "Build Date" => Time.new.to_s,
               "Built by" => "CircleCI",
             }
           )
end
